# spring
spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root
# mybatis
mybatis:
  mapper-locations: