# Spring
spring:
  datasource:
    url: jdbc:mysql:///classroom?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root
# Mybatis
mybatis:
  mapper-locations: classpath:com/xrafece/mapper/*.xml
  type-aliases-package: com.xrafece.entity
  configuration:
    map-underscore-to-camel-case: true
controller:
  sc: oneo
