# Spring
spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
# Mybatis
mybatis:
  type-aliases-package: com.xrafece.entity
  mapper-locations: classpath:com/xrafece/mapper/*.xml
